{{- if .Values.backendDeployment.autoscaling.enabled }}
{{- $deploymentName := include "todolist.backendDeployment.name" . -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $deploymentName }}
  labels:
    {{- include "todolist.backend.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $deploymentName }}
  minReplicas: {{ .Values.backendDeployment.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.backendDeployment.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.backendDeployment.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.backendDeployment.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.backendDeployment.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.backendDeployment.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
