{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "todolist.serviceAccountName" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
    {{- include "todolist.serviceAccount.labels" . | nindent 4 }}
  annotations:
    {{- include "todolist.serviceAccount.annotations" . | nindent 4 }}
{{- end }}
